E2e function test
aziontech/azion-framework-adapter pull request #30
Opened 2022-10-27 13:58 UTC by enicio

2022-10-28 15:17 UTC, augustollenz requested changes

2022-10-28 15:17 UTC, augustollenz commented on test/e2e-test/flareact-function.test.ts
> +import util = require('node:util');
We need to merge this file with flareact.test.js to avoid code duplication and to avoid run the same test twice.

2022-10-28 15:18 UTC, augustollenz commented on test/e2e-test/flareact-function.test.ts
> +import util = require('node:util');
Actually this comment applies to whole file not to this specific line :)

2022-11-04 13:42 UTC, augustollenz requested changes

2022-11-04 13:42 UTC, augustollenz commented on test/e2e-test/flareact.test.ts
> +            it('Try to publish only function with wrong token and expect to fail', async () => {
Try to reprhase to avoid duplication between describe and it.

2022-11-04 14:05 UTC, augustollenz approved these changes

2022-11-04 14:13 UTC, MagnunAVFAzion approved these changes

2022-11-04 14:28 UTC, merged