Feat/apply nextjs version checker
aziontech/azion-framework-adapter pull request #54
Opened 2023-02-20 18:34 UTC by ChernoBen

- static class that checks nextjs version

2023-02-22 20:39 UTC, olivmath requested changes

2023-02-22 20:39 UTC, olivmath commented on src/utils/version-checker/node-checker/node-checker.ts
> +    public static check():boolean{
linter here

2023-02-23 18:26 UTC, MagnunAVFAzion submitted a review, later dismissed
LGTM 🤘

2023-02-23 18:42 UTC, ChernoBen commented on src/utils/version-checker/version-checker.ts
> +            return true;
This method just needs to ensure that a given project is a azion nextjs project. So if its not, the verification ends at this stage.

2023-02-23 18:56 UTC, enicio commented on src/main.ts
> +try{
displayError just logs a console.log of the error, maybe that's why it doesn't stop the program. I think try catch wouldn't need to involve the whole program.

2023-02-23 19:02 UTC, olivmath submitted a review, later dismissed

2023-02-23 20:42 UTC, MagnunAVFAzion approved these changes

2023-02-23 20:43 UTC, enicio approved these changes

2023-02-23 20:44 UTC, merged