feat: nextjs static build
aziontech/azion-framework-adapter pull request #58
Opened 2023-03-01 21:13 UTC by enicio

2023-03-15 18:08 UTC, MagnunAVFAzion requested changes

2023-03-15 18:08 UTC, MagnunAVFAzion commented on test/e2e-test/nextjs.test.ts
> +describe.only('Create nextjs static application', () => {
we have to remove this only.

2023-03-15 18:18 UTC, MagnunAVFAzion requested changes

2023-03-16 17:21 UTC, MagnunAVFAzion approved these changes

2023-03-16 18:14 UTC, augustollenz approved these changes

2023-03-16 18:55 UTC, merged